language: node_js

services:
  - docker

before_install:
  - echo $(docker --version)
  - echo $(docker-compose --version)

install:
  - docker-compose up -d --build

script:
  - docker-compose run app npm run pre-commit

after_failure:
  - docker-compose logs
